### ISSUE TITLE
MacOS says the Installer can't be opened

### ISSUE THREAD

**Issue by babo4d** [LavaGang/MelonLoader.Installer#66]
App cannot be opened. Finder shows an error `The application “MelonLoader Installer.app” can’t be opened.` while `open` command shows the following error message.
```
> open /Applications/MelonLoader\ Installer.app
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600002359770 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

This is due to missing permissions. Can be fixed by adding executable permission to the app binary.
```
chmod +x "/Applications/MelonLoader Installer.app/MelonLoader.Installer.MacOS"
```

Also needs to be unquarantined, this is normal for unsigned apps downloaded from the internet, will always be required unless signed with a paid Apple developer account.
```
xattr -d com.apple.quarantine -r "/Applications/MelonLoader Installer.app"
```

**Comment by babo4d** [comment]
Same problem as of version `4.2.1`, does not seem like this is fixed by #87.

**Comment by trulyunknowable** [comment]
This bug is still unresolved. After opening the dmg and moving the app to the applications folder, double clicking results in this message:

“MelonLoader Installer” is damaged and can’t be opened. You should move it to the Trash.

**Comment by babo4d** [comment]
The original permissions issue is resolved in v4.3.0 by #121. The app still requires bypassing gatekeeper to launch which is expected behavior for unsigned code.

**Comment by HerpDerpinstine** [comment]
Reopening this issue to make it clear that it still requires being unquarantined
